### ISSUE TITLE
How to play only one Sound at a time

### ISSUE THREAD

**Issue by takaaptech** [Gasparfx/SoundManager#1]
I have begin.mp3 and i call:

SoundManager.PlaySound("begin");

How to ensure that only one "begin" sound play at specific of time? 

Thank so much!

**Comment by Gasparfx** [comment]
Hello!
You can add this code to SoundManager.cs:
```
    public static bool IsSoundPlaying(string name)
    {
        foreach (SMSound sound in Instance._sounds)
        {
            if (sound.Name == name)
                return true;
        }
        return false;
    }
```
Then you can check if sound playing before start new one
```
if (!SoundManager.IsSoundPlaying("begin"))
  SoundManager.PlaySound("begin");
```

**Comment by takaaptech** [comment]
Ok Thank so much! I hope you will update this code to this repo so i can pull and get the lastest update!
