### ISSUE TITLE
thx a lot!

### ISSUE THREAD

**Issue by raveneer** [Gasparfx/SoundManager#3]
your code looks nice and clean! good job!

and, how about using object pooling?

**Comment by Gasparfx** [comment]
Thanks!
I dont think that object pooling will change much here. What should we pool? GameObjects and AudioSources? This can be created really quick. Audio data? Yes, but in this case all sounds will be in memory. We can pool only few sounds. But for this its simplier to just keep links to them and play it with PlaySound(AudioClip clip).
If you profiled something in your game and has lags, can you post some details here?

**Comment by raveneer** [comment]
sure. if I have a performance issue, will post here.
